### ISSUE TITLE
Segfault in ClockServer on ackData_cleanup

### ISSUE THREAD

**Issue by Infrasonics** [camilleg/clockkit#1]
I ran into a SIGSEGV while using the PhaseLockedClock with a remote server.

After some investigation I found this to happen in `ClockServer::updateEntry`. First the `erase` on the `std::map` deletes an entry, after that the loop moves the iterator further and invalidates it by skipping an element.

EDIT:
My setup is Linux, amd64, gcc-9.3 with exactly two clients, where one is running on the same machine as the `ckserver`.

~I'll offer a PR with a simple fix.~ The PR provided fixes this in my case.

**Comment by camilleg** [comment]
Clear bug description and fix by Infrasonics.
