### ISSUE TITLE
[Feature Suggestion] FFI for Rust

### ISSUE THREAD

**Issue by Infrasonics** [camilleg/clockkit#3]
Hello,

currently I'm using *clockkit* in a project which I wrote in Rust. SWIG is not supporting Rust at the moment. To use it, I made a temporary FFI which works fine as long as there are no exceptions thrown (Rust doesn't have those). For now that is fine in my case. But in order to make it useful for others too, I wouldn'd mind doing things properly. Before investing the time though, I wanted to ask whether you would be willing to include the wrapper file in *clockkit* (and probably answer some questions so the interface ends up sensible).

My **two main concerns** here are:
1. My proposed FFI is a bit different from the ones you are currently providing for Ruby and Tcl, as follows:
1.1 In order to create a `PhaseLockedClock` with a configuration file for which one does not need root access, I exposed the corresponding method in `ConfigReader`.
1.2 To handle the lifetime properly I made a clock an object like it is in C++ too.
1.3 Methods currently exposed are:
    - `is_synchronized()`
    - `get_offset()`
    - `get_value()` (raw timesstamp as integer)
    - and some methods to give a `DateTime` value as a timestamp
2. From what I've read, it is good practice to make so called *sys-crates* buildable without network access. The easiest way to do that would be to simply put the third party code into the crate.
    - Would that be acceptable to you?
    - I would ask you to tag at least one version with a number so it can be properly referenced

To indicate various state changes, the Rust methods would return `Result`s with enum instances corresponding to the exceptions, e.g. `clockkit::error::Error::OutOfSync`. The candidates I have identified so far are:
    - `OutOfSync`
    - `Timeout`
    - `PacketError`
As this will be a high level interface I am unsure about the value of "lower level" exceptions like the *performance counter* frequency error or a *clock rollover*.

In addition to that, I would probably provide a patch to move the printing of the configuration in `ConfigReader` to a method. That method could be called in `clockkit.cpp` so the output would not change, yet the exposed FFI would not print anything when creating a clock as part of another project.

I would appreciate to hear your feedback on this; and hope that, with another easy interface to this cool project, more people will be able to make use of it.

**Comment by camilleg** [comment]
Yes, by all means let's add such a wrapper to _clockkit_.
Addressing concern #1 hardly damages the current FFIs, and may simplify later FFIs to other non-exception languages.
For concern #2 I defer to your Rust expertise. Let's tag that as v1.2.

Just to get things rolling, for now those lower-level exceptions might just be ignored, in the venerable tradition of "if you can't handle an error condition, don't test for it."
As this feature takes shape, if GitHub Issues is too formal for the two of us to hash things out, please reach me at http://camille-g.com/ and we'll choose a more lightweight channel for conversation.

**Comment by camilleg** [comment]
Everything's been implemented for a while now.
